---
- name: Install and Configure Jenkins, docker and kubernetes on Master Node
  hosts: react
  become: yes
  vars:
    - dest: /home/ansible/ansible/
  roles:
    - jenkins
    - docker
    - kubernetes-master
  tasks:
    - name: Fetch files from github
      git:
        repo: 'https://github.com/Noorunnsa/React-App.git'
        dest: "{{ dest }}"
        force: yes
    - name: Fetch the join command from the Master Node
      fetch: 
        src: /home/react/join_command.sh
        dest: /tmp/join_command.sh
        flat: yes
    - name: Add user react to the docker group
      user:
        name: react
        group: docker
- name: Install and configure Docker and Kubernetes and Copy the join command
  hosts: worker-node
  become: yes
  roles:
    - docker
    - kubernetes-worker
  tasks:
    - name: Copy the Join command to the Worker Node
      copy:
        src: /tmp/join_command.sh
        dest: /home/worker-node/join_command.sh
    - name: Add user worker-node to the docker group
      user:
        name: worker-node
        group: docker
