---
- name: Play to provision the required tools on the Control-Plane Node
  hosts: react
  become: yes
  tasks:
    - name: Install Java and Jenkins
      include_tasks: jenkins.yaml
    - name: Install docker
      include_tasks: docker.yaml
    - name: Add user react to the docker group #Assuming a user "react" is created and is added to sudoers file.
      user:
        name: react
        group: docker
    - name: Install and Configure Kubernetes using Kubeadm
      include_tasks: kubernetes-master.yaml
    - name: Fetch the join command from the Master Node
      fetch:
        src: /home/react/join_command.sh
        dest: /tmp/join_command.sh
        flat: yes
- name: Play to provision the required tools on the Worker-Node
  hosts: worker-node
  become: yes
  tasks:
    - name: Install Docker
      include_tasks: docker.yaml
    - name: Add user worker-node to the docker group # Assuming a user 'worker-node' is created and added to sudoers file.
      user:
        name: worker-node
        group: docker
     - name: Copy the Join command to the Worker Node
      copy:
        src: /tmp/join_command.sh
        dest: /home/worker-node/join_command.sh
    - name: Install kubelet, kubectl and kubeadm
      include-tasks: kubernetes-worker.yaml
