---
packages:
 - apt-transport-https
 - ca-certificates
 - curl
 - gnupg-agent
 - gpg
 - software-properties-common
repo_url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
k8s_packages:
-  kubelet
-  kubeadm
-  kubectl
