---
- name: Restart kubelet
  service:
      name: kubelet
      daemon_reload: yes
      state: restarted
- name: Restart Docker
  service: 
     name: docker 
     state: restarted
- name: Restart Containerd
  service:
    name: containerd
    state: restarted
